SET(prefix "/svr/htdocs/test/xunsearch")
SET(exec_prefix "${prefix}")
SET(XAPIAN_LIBRARIES "${exec_prefix}/lib/libxapian.dylib" CACHE FILEPATH "Libraries for Xapian")
SET(XAPIAN_INCLUDE_DIR "${prefix}/include" CACHE PATH "Include path for Xapian")
SET(XAPIAN_FOUND "TRUE")
