document.writeln("<div id=\"ckepop\" style=\"padding:0px 98px;\">");
document.writeln("<a href=\"http://www.jiathis.com/share/\" class=\"jiathis jiathis_txt jtico jtico_jiathis\" target=\"_blank\">∑÷œÌµΩ£∫</a>");
document.writeln("<a class=\"jiathis_button_qzone\"></a>");
document.writeln("<a class=\"jiathis_button_tsina\"></a>");
document.writeln("<a class=\"jiathis_button_taobao\"></a>");
document.writeln("<a class=\"jiathis_button_kaixin001\"></a>");
document.writeln("<a class=\"jiathis_button_renren\"></a>");
document.writeln("<a class=\"jiathis_button_51\"></a>");
document.writeln("<a class=\"jiathis_button_douban\"></a>");
document.writeln("<a class=\"jiathis_button_digu\"></a>");
document.writeln("<a class=\"jiathis_button_fanfou\"></a>");
document.writeln("<a class=\"jiathis_button_xianguo\"></a>");
document.writeln("<a class=\"jiathis_button_zhuaxia\"></a>");
document.writeln("<a class=\"jiathis_button_hexun\"></a>");
document.writeln("<a class=\"jiathis_button_baidu\"></a>");
document.writeln("<a class=\"jiathis_button_google\"></a>");
document.writeln("<a class=\"jiathis_button_yahoo\"></a>");
document.writeln("<a class=\"jiathis_button_youdao\"></a>");
document.writeln("<a class=\"jiathis_button_115\"></a>");
document.writeln("<a class=\"jiathis_button_114la\"></a>");
document.writeln("<a class=\"jiathis_button_follow5\"></a>");
document.writeln("<a class=\"jiathis_button_qq\"></a>");
document.writeln("<a class=\"jiathis_button_tqq\"></a>");
document.writeln("<a class=\"jiathis_button_tsohu\"></a>");
document.writeln("<a class=\"jiathis_button_t163\"></a>");
document.writeln("<a class=\"jiathis_button_thexun\"></a>");
document.writeln("<a class=\"jiathis_button_tsina\"></a>");
document.writeln("<a class=\"jiathis_button_blogsina\"></a>");
document.writeln("<a class=\"jiathis_button_tieba\"></a>");
document.writeln("<a class=\"jiathis_button_feixin\"></a>");
document.writeln("<a class=\"jiathis_button_ganniu\"></a>");
document.writeln("<a class=\"jiathis_button_sohu\"></a>");
document.writeln("<a class=\"jiathis_button_tianya\"></a>");
document.writeln("<a class=\"jiathis_button_hotmail\"></a>");
document.writeln("<a class=\"jiathis_button_gmail\"></a>");
document.writeln("<a class=\"jiathis_button_i139\"></a>");
document.writeln("</div>");
